[project]
name = "studytime-tui"
version = "0.2.0"
description = "Simple TUI program to track and display time spent studying."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["textual>=6.11.0,<7", "textual-plotext>=1.0.1,<2"]
